In [4]:
report_title = pd.read_excel(
    file_path,
    sheet_name="Данные",
    header=None,
    nrows=1
).iloc[0, 0]

# Veriyi oku
df = pd.read_excel(
    file_path,
    sheet_name="Данные",
    header=1
)

df.columns = df.columns.str.strip()
df = df.dropna(how="all").reset_index(drop=True)

df.head()

,Номенклатура,Поставщик,Производитель,Количество продажи,Сумма продажи,Цена продажи,Адрес,Номер накладной,Дата накладной
0,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,-,Н-11-00-11,2025-04-01
1,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,-,Н-11-00-12,2025-04-01
2,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,-,Н-11-00-13,2025-04-01
3,Продукт 2,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,-,Н-11-00-14,2025-04-02
4,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,-,Н-11-00-15,2025-04-03

In [6]:
str_cols = df.select_dtypes(include="object").columns

# Baştaki/sondaki boşlukları sil
df[str_cols] = df[str_cols].apply(lambda x: x.str.strip())

# Birden fazla boşluğu tek boşluğa indir
df[str_cols] = df[str_cols].apply(lambda x: x.str.replace(r"\s+", " ", regex=True))

# "-" veya sadece boşluk içeren değerleri NaN yap
df[str_cols] = df[str_cols].apply(lambda x: x.replace(r"^\s*-\s*$", pd.NA, regex=True))

# Boş stringleri NaN yap
df[str_cols] = df[str_cols].apply(lambda x: x.replace("", pd.NA))

# Kolon isimlerini de temizle
df.columns = df.columns.str.strip().str.replace(r"\s+", " ", regex=True)


df.head(10)

,Номенклатура,Поставщик,Производитель,Количество продажи,Сумма продажи,Цена продажи,Адрес,Номер накладной,Дата накладной
0,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,Н-11-00-11,2025-04-01
1,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,Н-11-00-12,2025-04-01
2,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,Н-11-00-13,2025-04-01
3,Продукт 2,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,Н-11-00-14,2025-04-02
4,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,Н-11-00-15,2025-04-03
5,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,<NA>,NaN,2025-04-03
6,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 2,1,100,100,<NA>,Н-11-00-16,2025-04-01
7,Продукт 2,Поставщик 2 г. Москва,ООО Производитель номер 2,1,100,100,<NA>,Н-11-00-17,2025-04-02
8,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 2,1,100,100,<NA>,Н-11-00-18,2025-04-03
9,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 2,1,100,100,<NA>,Н-11-00-19,2025-04-03

In [8]:
df.drop("Адрес", axis=1, inplace=True)

df.head()

,Номенклатура,Поставщик,Производитель,Количество продажи,Сумма продажи,Цена продажи,Номер накладной,Дата накладной
0,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,Н-11-00-11,2025-04-01
1,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,Н-11-00-12,2025-04-01
2,Продукт 1,Поставщик 1 г. Москва,ООО Производитель номер 1,1,100,100,Н-11-00-13,2025-04-01
3,Продукт 2,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,Н-11-00-14,2025-04-02
4,Продукт 3,Поставщик 2 г. Москва,ООО Производитель номер 1,1,100,100,Н-11-00-15,2025-04-03

In [11]:
df["Город"] = df["Поставщик"].str.extract(r"г\.\s*([А-Яа-яA-Za-z\- ]+)")

# Поставщик kolonundan şehir kısmını kaldır
df["Поставщик"] = df["Поставщик"].str.replace(r"\s*г\.\s*[А-Яа-яA-Za-z\- ]+", "", regex=True)

# Temizlik (boşluk vs.)
df["Поставщик"] = df["Поставщик"].str.strip()
df["Город"] = df["Город"].str.strip()

# Kontrol
print(df[["Поставщик", "Город"]].head())

     Поставщик   Город
0  Поставщик 1  Москва
1  Поставщик 1  Москва
2  Поставщик 1  Москва
3  Поставщик 2  Москва
4  Поставщик 2  Москва

In [13]:
df.head(10)

,Номенклатура,Поставщик,Производитель,Количество продажи,Сумма продажи,Цена продажи,Номер накладной,Дата накладной,Город
0,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-11,2025-04-01,Москва
1,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-12,2025-04-01,Москва
2,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-13,2025-04-01,Москва
3,Продукт 2,Поставщик 2,ООО Производитель номер 1,1,100,100,Н-11-00-14,2025-04-02,Москва
4,Продукт 3,Поставщик 2,ООО Производитель номер 1,1,100,100,Н-11-00-15,2025-04-03,Москва
5,Продукт 3,Поставщик 2,ООО Производитель номер 1,1,100,100,NaN,2025-04-03,Москва
6,Продукт 1,Поставщик 1,ООО Производитель номер 2,1,100,100,Н-11-00-16,2025-04-01,Москва
7,Продукт 2,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-17,2025-04-02,Москва
8,Продукт 3,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-18,2025-04-03,Москва
9,Продукт 3,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-19,2025-04-03,Москва

In [16]:
# --- TARİH PARÇALAMA ---

df["Год"] = df["Дата накладной"].dt.year
df["Месяц"] = df["Дата накладной"].dt.month
df["День"] = df["Дата накладной"].dt.day

print(df[["Год", "Месяц" ,"День"]].head())

    Год  Месяц  День
0  2025      4     1
1  2025      4     1
2  2025      4     1
3  2025      4     2
4  2025      4     3

In [19]:
month_dict = {
    1: "Январь", 2: "Февраль", 3: "Март", 4: "Апрель",
    5: "Май", 6: "Июнь", 7: "Июль", 8: "Август",
    9: "Сентябрь", 10: "Октябрь", 11: "Ноябрь", 12: "Декабрь"
}

df["Месяц"] = df["Месяц"].map(month_dict)

df["Месяц"].head()

0    Апрель
1    Апрель
2    Апрель
3    Апрель
4    Апрель
Name: Месяц, dtype: object

In [24]:
df.isna().sum()[df.isna().sum() > 0]

Номер накладной    1
dtype: int64

In [26]:
df.head(10)

,Номенклатура,Поставщик,Производитель,Количество продажи,Сумма продажи,Цена продажи,Номер накладной,Дата накладной,Город,Год,Месяц,День
0,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-11,2025-04-01,Москва,2025,Апрель,1
1,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-12,2025-04-01,Москва,2025,Апрель,1
2,Продукт 1,Поставщик 1,ООО Производитель номер 1,1,100,100,Н-11-00-13,2025-04-01,Москва,2025,Апрель,1
3,Продукт 2,Поставщик 2,ООО Производитель номер 1,1,100,100,Н-11-00-14,2025-04-02,Москва,2025,Апрель,2
4,Продукт 3,Поставщик 2,ООО Производитель номер 1,1,100,100,Н-11-00-15,2025-04-03,Москва,2025,Апрель,3
5,Продукт 3,Поставщик 2,ООО Производитель номер 1,1,100,100,NaN,2025-04-03,Москва,2025,Апрель,3
6,Продукт 1,Поставщик 1,ООО Производитель номер 2,1,100,100,Н-11-00-16,2025-04-01,Москва,2025,Апрель,1
7,Продукт 2,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-17,2025-04-02,Москва,2025,Апрель,2
8,Продукт 3,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-18,2025-04-03,Москва,2025,Апрель,3
9,Продукт 3,Поставщик 2,ООО Производитель номер 2,1,100,100,Н-11-00-19,2025-04-03,Москва,2025,Апрель,3

In [42]:
cols = [c for c in df.columns if c != "Номер накладной"]

mask_group = (
    df.duplicated(subset=cols, keep=False) &
    df.groupby(cols, dropna=False)["Номер накладной"]
      .transform(lambda x: x.isna().any() and x.notna().any())
)

# SADECE NaN olan satırları seç
mask_nan = mask_group & df["Номер накладной"].isna()

def highlight(row):
    if mask_nan.loc[row.name]:
        return ["background-color: red"] * len(row)
    elif mask_group.loc[row.name]:
        return ["background-color: yellow"] * len(row)
    return [""] * len(row)

df.style.apply(highlight, axis=1)

In [50]:
df["Дата накладной"] = df["Дата накладной"].dt.date

In [51]:
output_path = r"C:\Users\husnu\OneDrive\Desktop\interview\Имя_клиента_sale_10.0_2026-04_cleaned.xlsx"
df.to_excel(output_path, index=False)